# Generated by Django 2.2.1 on 2020-06-26 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='userslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userslot',
            name='washing_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_booking.WashingMachineSlot'),
        ),
    ]
