# Generated by Django 2.2.1 on 2020-06-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0007_auto_20200626_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userslot',
            old_name='washing_machine',
            new_name='washing_machine_slot',
        ),
    ]
